import { Helmet } from 'react-helmet-async'
import { ArrowRight, ChevronRight, CircleCheck, Compass, Gauge, Search } from 'lucide-react'
import { Link, Navigate, useParams } from 'react-router-dom'
import Accordion from '../components/ui/Accordion'
import Button from '../components/ui/Button'
import CTABand from '../components/sections/CTABand'
import Preheading from '../components/ui/Preheading'
import Reveal from '../components/ui/Reveal'
import { getServicePage, servicePages } from '../data/servicePageData'

const baseUrl = 'https://www.digitalisglobal.com/au/services'

export default function ServicePage() {
  const { slug } = useParams()
  const service = getServicePage(slug)
  if (!service) return <Navigate to="/au/services" replace />
  const canonical = `${baseUrl}/${service.slug}`
  const title = `${service.title} Australia | Digitalis Global`
  const description = `${service.description} Work with Digitalis Global for ${service.title.toLowerCase()} tailored to Australian business goals.`
  const faqItems = service.faqs.map(([question, answer]) => ({ question, answer }))
  const schema = [
    { '@context': 'https://schema.org', '@type': 'Service', name: `${service.title} Australia`, description: service.description, url: canonical, image: `https://www.digitalisglobal.com${service.image}`, provider: { '@type': 'Organization', name: 'Digitalis Global', url: 'https://www.digitalisglobal.com/au' }, areaServed: { '@type': 'Country', name: 'Australia' }, serviceType: service.title },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.digitalisglobal.com/au' }, { '@type': 'ListItem', position: 2, name: 'Services', item: baseUrl }, { '@type': 'ListItem', position: 3, name: service.title, item: canonical }] },
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqItems.map((faq) => ({ '@type': 'Question', name: faq.question, acceptedAnswer: { '@type': 'Answer', text: faq.answer } })) },
  ]
  return <><Helmet><title>{title}</title><meta name="description" content={description} /><link rel="canonical" href={canonical} /><link rel="alternate" hrefLang="en-AU" href={canonical} /><link rel="alternate" hrefLang="x-default" href={canonical} /><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1" /><meta property="og:type" content="website" /><meta property="og:title" content={title} /><meta property="og:description" content={description} /><meta property="og:image" content={`https://www.digitalisglobal.com${service.image}`} /><meta property="og:locale" content="en_AU" /><meta name="twitter:card" content="summary_large_image" />{schema.map((item, index) => <script key={index} type="application/ld+json">{JSON.stringify(item)}</script>)}</Helmet>
    <section className="relative isolate overflow-hidden bg-brand-dark px-6 pb-20 pt-32 text-white md:px-8 md:pb-28 md:pt-44"><div className="pointer-events-none absolute inset-0 opacity-25"><img src={service.image} alt="" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-brand-dark/90" /></div><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_78%_25%,rgba(14,165,233,0.32),transparent_25%)]" /><div className="relative mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-9 flex flex-wrap items-center gap-2 text-sm text-slate-300"><Link to="/au" className="hover:text-white">Home</Link><ChevronRight className="h-4 w-4" /><Link to="/au/services" className="hover:text-white">Services</Link><ChevronRight className="h-4 w-4" /><span className="text-cyan-200">{service.title}</span></nav><Reveal><Preheading className="text-cyan-200">{service.title} for Australian businesses</Preheading><h1 className="mt-6 max-w-4xl font-display text-4xl font-extrabold leading-[1.06] tracking-tight sm:text-5xl lg:text-7xl">{service.headline}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200 md:text-xl">{service.intro}</p><div className="mt-10"><Button as="a" href="#contact" variant="primary" className="gap-4 px-6 py-3.5">Book a free strategy call <ArrowRight className="h-4 w-4" /></Button></div></Reveal></div></section>
    <section className="bg-white px-6 py-20 md:px-8 md:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><Preheading>What we do</Preheading><h2 className="mt-4 font-display text-3xl font-bold tracking-tight text-brand md:text-5xl">Built around the work that creates momentum.</h2></Reveal><Reveal><div className="grid gap-4 sm:grid-cols-2">{service.deliverables.map((item) => <div key={item} className="rounded-2xl border border-brand/10 bg-brand-light p-5"><CircleCheck className="h-6 w-6 text-cyan-600" /><p className="mt-4 font-semibold leading-6 text-brand">{item}</p></div>)}</div></Reveal></div></section>
    <section className="bg-brand-light px-6 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><Reveal className="max-w-3xl"><Preheading>What good looks like</Preheading><h2 className="mt-4 font-display text-3xl font-bold tracking-tight text-brand md:text-5xl">A clearer route from effort to outcome.</h2></Reveal><div className="mt-12 grid gap-5 md:grid-cols-3">{service.outcomes.map((outcome, index) => { const Icon = [Compass, Gauge, Search][index]; return <Reveal key={outcome} className="rounded-3xl bg-white p-8 shadow-sm"><Icon className="h-7 w-7 text-cyan-600" /><p className="mt-6 font-display text-xl font-bold text-brand">{outcome}</p></Reveal> })}</div></div></section>
    <section className="bg-white px-6 py-20 md:px-8 md:py-32"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><Preheading>Our approach</Preheading><h2 className="mt-4 font-display text-3xl font-bold tracking-tight text-brand md:text-5xl">Practical, connected and transparent.</h2><p className="mt-6 leading-8 text-neutral-600">Every engagement starts with your customers, commercial priorities and current digital reality. We then focus effort where it is most likely to help.</p></Reveal><Reveal className="space-y-4">{['Understand the opportunity and baseline', 'Prioritise the work with the strongest potential impact', 'Build, launch and measure with clarity', 'Keep improving what the data and customers tell us'].map((step, index) => <div key={step} className="flex gap-5 rounded-2xl border border-brand/10 p-5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-brand font-bold text-cyan-300">0{index + 1}</span><p className="pt-1 font-semibold text-brand">{step}</p></div>)}</Reveal></div></section>
    <section className="bg-brand-light px-6 py-20 md:px-8 md:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><Preheading>Service FAQ</Preheading><h2 className="mt-4 font-display text-3xl font-bold tracking-tight text-brand md:text-5xl">Useful answers, before we talk.</h2></Reveal><Reveal><Accordion items={faqItems} /></Reveal></div></section>
    <section className="bg-white px-6 py-16 md:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-cyan-700">Explore more services</p><div className="mt-5 flex flex-wrap gap-3">{servicePages.filter((item) => item.slug !== service.slug).map((item) => <Link key={item.slug} to={`/au/services/${item.slug}`} className="rounded-full border border-brand/15 px-4 py-2 text-sm font-semibold text-brand transition hover:border-cyan-400 hover:bg-cyan-50">{item.title}</Link>)}</div></div></section><CTABand /></>
}
